### ISSUE TITLE
Replace! Hecate

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dane-video-segmentation-worker#38]
Shots seem overly strict, keyframes quite generous. 

ffmpeg can also do scene detection
Philo & A-team have looked into tools for keyframes & scenes > find report
DAAN also stores keyframes (low res) - use timestamps?

**Comment by Veldhoen** [comment]
https://www.scenedetect.com/

**Comment by Veldhoen** [comment]
Other option: artificially reduce the number of keyframes, e.g. by sampling a limited number per shot

**Comment by jblom** [comment]
the code to replace Hecate was tested and merged: https://github.com/beeldengeluid/dane-video-segmentation-worker/pull/39

Currently I'm running the elfstendentoch query, which seems to go well (also using just 4Gi of memory instead of 17Gi)
